title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          blocks:
            type: blocks
  sidebar:
    width: 1/3
    sections:
      pages:
        label:
          en: Child-Pages
          de: Unterseiten
        type: pages
        template: default
      files:
        type: files
        label:
          en: Page-Files
          de: Dateien dieser Seite

